local util = require("power-finder.util")

describe("util.trim", function()
  it("trims surrounding whitespace", function()
    assert.equals("foo", util.trim("  foo  "))
    assert.equals("foo bar", util.trim("\tfoo bar\n"))
  end)
  it("handles nil and empty", function()
    assert.equals("", util.trim(nil))
    assert.equals("", util.trim("   "))
  end)
end)

describe("util.split_csv", function()
  it("splits on commas and trims", function()
    assert.same({ "*.ts", "*.tsx" }, util.split_csv("*.ts, *.tsx"))
  end)
  it("drops empty entries", function()
    assert.same({ "a", "b" }, util.split_csv(" a , , b ,"))
  end)
  it("returns empty for nil/blank", function()
    assert.same({}, util.split_csv(nil))
    assert.same({}, util.split_csv("   "))
  end)
  it("preserves spaces inside a glob (only commas split)", function()
    assert.same({ "src/my dir/**", "*.lua" }, util.split_csv("src/my dir/**, *.lua"))
  end)
end)

describe("util.byte_to_cell", function()
  it("counts ascii as one cell each", function()
    assert.equals(3, util.byte_to_cell("abcdef", 3))
  end)
  it("counts multibyte display width correctly", function()
    -- "日本" = 6 bytes, 4 display cells (2 each). byte offset 6 -> 4 cells.
    assert.equals(4, util.byte_to_cell("日本x", 6))
  end)
end)

describe("util.shorten", function()
  it("keeps short paths intact", function()
    assert.equals("a/b.lua", util.shorten("a/b.lua", 20))
  end)
  it("elides the head of long paths, keeping the tail", function()
    local s = util.shorten("aaaaaaaaaaaaaaaaaaaa/b.lua", 10)
    assert.is_true(#s < #"aaaaaaaaaaaaaaaaaaaa/b.lua")
    assert.equals("…", s:sub(1, 3)) -- ellipsis prefix (3 bytes)
    assert.is_true(s:sub(-5) == "b.lua") -- tail preserved
  end)
end)
